### ISSUE TITLE
Replace's viem's recoveryAddresss

### ISSUE THREAD

**Issue by wanderer** [masslbs/Tennessine#53]
We should just use an sync function here.

**Comment by BZAghalarov** [comment]
@wanderer ,
due to the issue logic is not fully clear&short I want to clarify a question before moving to final solution.

There is not any `recoveryAddress` (I believe the ending with 3 "s"'s is typo') function in [https://github.com/masslbs/Tennessine/](https://github.com/masslbs/Tennessine/).
As I understood the context is about the "recoverMessageAddress" function usage in `stream.ts` file.
	
If your answer is positive, I already changed the `pull` method there and related testcase as [draft PR.](https://github.com/masslbs/Tennessine/pull/105) , please review it.

Let me know if I wrongly understood something or I should do something different.
